apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: cboe-test
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "cboe-test:latest"
  mainApplicationFile: "local:///opt/spark/work-dir/main.py"
  arguments: ['--job=marketing_data_intake']
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: cboe-test-spark
    env:
      - name: SPARK_PRINT_LAUNCH_COMMAND
        value: "1"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0